=== jvenureddy/OracleSOASuite/CustomerTestBiz/xsd/CustomerTestBiz.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://soa.grupovidanta.com/CustomerTestBiz"
            targetNamespace="http://soa.grupovidanta.com/CustomerTestBiz"
            xmlns:vid="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz"
            elementFormDefault="qualified">
  <xsd:import schemaLocation="VidantaCommons.xsd"
              namespace="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz"/>
  <xsd:element name="FindCustomersRq">
    <xsd:annotation>
      <xsd:documentation>
        A sample element
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="CustomerID" type="xsd:integer" minOccurs="0"
                     maxOccurs="1"/>
        <xsd:element name="FirstName" type="xsd:string" maxOccurs="1"
                     minOccurs="0"/>
        <xsd:element name="LastName" type="xsd:string" maxOccurs="1"
                     minOccurs="0"/>
        <xsd:element name="Email" type="xsd:string" maxOccurs="1"
                     minOccurs="0"/>
        <xsd:element name="UserName" type="xsd:string" minOccurs="0"
                     maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="FindCustomersRs">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Success" minOccurs="0" maxOccurs="1"
                     type="vid:SuccessType"/>
        <xsd:element name="Customers" type="tns:CustomersType"/>
        <xsd:element name="Errors" type="vid:ErrorsType" minOccurs="0"
                     maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="CustomerBasicInfoType">
    <xsd:sequence>
       <xsd:element name="ID" type="xsd:integer"/>
       <xsd:element name="Name" type="xsd:string"/>
       <xsd:element name="LastName" type="xsd:string"/>
       <xsd:element name="MiddleName" type="xsd:string"/>
       <xsd:element name="Gender" type="xsd:string"/>
       <xsd:element name="Email" type="xsd:string"/>
       <xsd:element name="UserName" type="xsd:string"/>
       <xsd:element name="Password" type="xsd:string"/>
       <xsd:element name="BirthDate" type="xsd:date"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="CustomerType">
    <xsd:sequence>
      <xsd:element name="BasicInformation" type="tns:CustomerBasicInfoType"/>
      <xsd:element name="Address" type="tns:AddressType"/>
      <xsd:element name="CreditCard" type="tns:CardType"/>
      <xsd:element name="AditionalInfo" type="tns:AditionalInfoType"/>
      <xsd:element name="Memebership" type="tns:MembershipType"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="AddressType">
    <xsd:sequence>
      <xsd:element name="City" type="xsd:string"/>
      <xsd:element name="State" type="xsd:string"/>
      <xsd:element name="ZipCode" type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="CardType">
    <xsd:sequence>
      <xsd:element name="Number" type="xsd:string"/>
      <xsd:element name="CVV" type="xsd:integer"/>
      <xsd:element name="ExpirationDate" type="xsd:date"/>
      <xsd:element name="Type" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="AditionalInfoType">
    <xsd:sequence>
      <xsd:element name="Company" type="xsd:string"/>
      <xsd:element name="Vehicle" type="xsd:string"/>
      <xsd:element name="TelephoneNumber" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="CustomersType">
    <xsd:annotation>
      <xsd:documentation>
        Contains a list of Customers
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="Customer" type="tns:CustomerType" minOccurs="0"
                   maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="MembershipType">
    <xsd:sequence>
      <xsd:element name="MembershipCategory" type="xsd:string"/>
      <xsd:element name="LoyaltyPoints" type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== jvenureddy/OracleSOASuite/CustomerTestBiz/testsuites/Transformation_1-Target.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<ns2:FindCustomersRs xmlns:ns2="http://soa.grupovidanta.com/CustomerTestBiz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://soa.grupovidanta.com/CustomerTestBiz file:/home/marco/jdeveloper/SOAEnvironmentTest/CustomerTestBiz/xsd/CustomerTestBiz.xsd">
   <ns2:Success/>
   <ns2:Customers>
      <ns2:Customer>
         <ns2:BasicInformation>
            <ns2:ID>1</ns2:ID>
            <ns2:Name>Name2</ns2:Name>
            <ns2:LastName>LastName3</ns2:LastName>
            <ns2:MiddleName>MiddleName4</ns2:MiddleName>
            <ns2:Gender>Gender5</ns2:Gender>
            <ns2:Email>Email6</ns2:Email>
            <ns2:UserName>UserName7</ns2:UserName>
            <ns2:Password>Password8</ns2:Password>
            <ns2:BirthDate>2014-10-27</ns2:BirthDate>
         </ns2:BasicInformation>
         <ns2:Address>
            <ns2:City>City9</ns2:City>
            <ns2:State>State10</ns2:State>
            <ns2:ZipCode>11</ns2:ZipCode>
         </ns2:Address>
         <ns2:CreditCard>
            <ns2:Number>Number12</ns2:Number>
            <ns2:CVV>13</ns2:CVV>
            <ns2:ExpirationDate>2014-10-27</ns2:ExpirationDate>
            <ns2:Type>Type14</ns2:Type>
         </ns2:CreditCard>
         <ns2:AditionalInfo>
            <ns2:Company>Company15</ns2:Company>
            <ns2:Vehicle>Vehicle16</ns2:Vehicle>
            <ns2:TelephoneNumber>TelephoneNumber17</ns2:TelephoneNumber>
         </ns2:AditionalInfo>
      </ns2:Customer>
      <ns2:Customer>
         <ns2:BasicInformation>
            <ns2:ID>18</ns2:ID>
            <ns2:Name>Name19</ns2:Name>
            <ns2:LastName>LastName20</ns2:LastName>
            <ns2:MiddleName>MiddleName21</ns2:MiddleName>
            <ns2:Gender>Gender22</ns2:Gender>
            <ns2:Email>Email23</ns2:Email>
            <ns2:UserName>UserName24</ns2:UserName>
            <ns2:Password>Password25</ns2:Password>
            <ns2:BirthDate>2014-10-27</ns2:BirthDate>
         </ns2:BasicInformation>
         <ns2:Address>
            <ns2:City>City26</ns2:City>
            <ns2:State>State27</ns2:State>
            <ns2:ZipCode>28</ns2:ZipCode>
         </ns2:Address>
         <ns2:CreditCard>
            <ns2:Number>Number29</ns2:Number>
            <ns2:CVV>30</ns2:CVV>
            <ns2:ExpirationDate>2014-10-27</ns2:ExpirationDate>
            <ns2:Type>Type31</ns2:Type>
         </ns2:CreditCard>
         <ns2:AditionalInfo>
            <ns2:Company>Company32</ns2:Company>
            <ns2:Vehicle>Vehicle33</ns2:Vehicle>
            <ns2:TelephoneNumber>TelephoneNumber34</ns2:TelephoneNumber>
         </ns2:AditionalInfo>
      </ns2:Customer>
      <ns2:Customer>
         <ns2:BasicInformation>
            <ns2:ID>35</ns2:ID>
            <ns2:Name>Name36</ns2:Name>
            <ns2:LastName>LastName37</ns2:LastName>
            <ns2:MiddleName>MiddleName38</ns2:MiddleName>
            <ns2:Gender>Gender39</ns2:Gender>
            <ns2:Email>Email40</ns2:Email>
            <ns2:UserName>UserName41</ns2:UserName>
            <ns2:Password>Password42</ns2:Password>
            <ns2:BirthDate>2014-10-27</ns2:BirthDate>
         </ns2:BasicInformation>
         <ns2:Address>
            <ns2:City>City43</ns2:City>
            <ns2:State>State44</ns2:State>
            <ns2:ZipCode>45</ns2:ZipCode>
         </ns2:Address>
         <ns2:CreditCard>
            <ns2:Number>Number46</ns2:Number>
            <ns2:CVV>47</ns2:CVV>
            <ns2:ExpirationDate>2014-10-27</ns2:ExpirationDate>
            <ns2:Type>Type48</ns2:Type>
         </ns2:CreditCard>
         <ns2:AditionalInfo>
            <ns2:Company>Company49</ns2:Company>
            <ns2:Vehicle>Vehicle50</ns2:Vehicle>
            <ns2:TelephoneNumber>TelephoneNumber51</ns2:TelephoneNumber>
         </ns2:AditionalInfo>
      </ns2:Customer>
   </ns2:Customers>
   <ns2:Errors>
      <vid:Error xmlns:vid="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz">
         <vid:ErrorCode>ErrorCode52</vid:ErrorCode>
         <vid:Description>Description53</vid:Description>
         <vid:BusinessProcess>BusinessProcess54</vid:BusinessProcess>
         <vid:FailedService>FailedService55</vid:FailedService>
         <vid:TimeStamp>2014-10-27T18:05:06.226</vid:TimeStamp>
      </vid:Error>
      <vid:Error xmlns:vid="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz">
         <vid:ErrorCode>ErrorCode56</vid:ErrorCode>
         <vid:Description>Description57</vid:Description>
         <vid:BusinessProcess>BusinessProcess58</vid:BusinessProcess>
         <vid:FailedService>FailedService59</vid:FailedService>
         <vid:TimeStamp>2014-10-27T18:05:06.226</vid:TimeStamp>
      </vid:Error>
      <vid:Error xmlns:vid="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz">
         <vid:ErrorCode>ErrorCode60</vid:ErrorCode>
         <vid:Description>Description61</vid:Description>
         <vid:BusinessProcess>BusinessProcess62</vid:BusinessProcess>
         <vid:FailedService>FailedService63</vid:FailedService>
         <vid:TimeStamp>2014-10-27T18:05:06.227</vid:TimeStamp>
      </vid:Error>
   </ns2:Errors>
</ns2:FindCustomersRs>
